if: tag IS blank
branches:
  only:
  - master
  - develop

sudo: required
dist: trusty

language: php
php:
- "7.2"

cache:
  directories:
  - vendor

before_install:
- wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
- echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
- sudo apt-get update
- sudo apt-get install -y --allow-unauthenticated cf-cli

install:
- composer self-update
- composer install --no-interaction
- npm install
- npm run dev

script:
- echo "No tests ran"

deploy:
- provider: script
  script: APP_ENV=staging API_URI=$STAGING_API_URI FRONTEND_URI=$STAGING_FRONTEND_URI CF_SPACE=$STAGING_CF_SPACE scripts/Deploy.sh
  skip_cleanup: true
  on:
    branch: develop
- provider: codedeploy
  revision_type: github
  access_key_id:
    secure: OKxfgePHuA6H3Kv0j2Wp5EKnRsEtqe6ZYsxsSaFS4Q4ew/LPuzbREkieifXLCbCpgiO63NaZMvyFPpDcEYfRmQ+ybiO50Vq2po3Je5p5weKB7poikSfg4QyDqOQ8WhAznergl+eBT0K/aGpJQgDgyIKjVcDYxaxXDpMkDw3zWNbmmyNtcEh3cdflJQMbjwyWei19bWLUrOEO5BFKW8GEFGP6H6vMUoSyAD+9ea6Wjcr9RrO+a/KN5KejH7yR/XjRQUd5UFHniWk4BzTgotEqaVi/XmoRQYHUpc8BY7OGIBC7yQt7Kg3XETD12tzpnzazx7rd4C6+Hirsbg/8vDEbvvAYQ8DuDGXwYillw22o8fqbBkSQVLXEEYV3HcX+/zU0HTFft9WuOQDR/VVKnV1OgdCYcNGJGoBNoWn2agFSJ/+DnXqDC1WqX8r2f6TVygl93SlybD3aYv3Mj9zoq006+bmVugVrFKCABg+n8z9z3ZLjvnvusuVzGareo/R2iKjLsdXhdQEtujBo60PAoru4QZlzhg2/B5nDTzB9U8k8c1PiP4Ob3MqoLRE08mg0WOWCUHjpENmsrfusiBa8eXgpXuF9Io3AFP8EN+kFbfrAuh7C05Yrwv5wvogYhWcNX3f8X4rQROHKO10idg7uFNG20HDtFpI0bUMPbqjIgtp8iGs=
  secret_access_key:
    secure: BR/gyquSZa/cwtTvPZ4sFQ6g/clMJM1oHpYpMaMd9adT7Em25br+lTIV6JdkT9JEXW6BNvvvmXENotO3CkxgZzRROutqrVl8i2z8VdeJXHmaN902+cpHYFejNkDpFdJt/7jbvoQJqxK6vE12jY/gouF9SQpUeCzlmOn7HtHI3a5dupLbTaTjqm9ByZud649hI+jp0BXMKN+2mU/etDANCSPtCvIJ2JTeSBHA0XZevHnqS6R7bobPgR20zC2XFsnQpT2PODeBDt6bxph4la6mO7kclGtipHm/OjRahj5FYss6GDXxdlVdYM5EBijjQ3yN7Njra0yK0NKLsfOBfY9FZeOboQ821qADPSGVRBt589F6M6o4qnH7deWa4J+OjRLppsm2FMlY/AECCky2yj8AGLaaIxzl2ybwAhIi7lgnnqfKSGG6hgPa2nYtiB/OftxoQmgTMjq/tOy2yseay92qVLnQF8l+TR65h01o2PhQo5bmjD/79vCS0hGel8m73sptkwKtotyZhMfqYV6CMt/DdB4KK9IIOOLA8dgowlsqjUB9aI/xtWtLH1p5nLzaUocNXqLLxgXIwZStZwVFCPQFzRiB6zaRUjPHMag+niJNJA61xafq58mAQ5JHPCZYmIRavwgRE13i4/IW7/lODg5qHWpz4hSyVwEKqjnzdphscBE=
  application: CK-Frontend
  deployment_group: CK-Frontend-Deployment-Production
  region: eu-west-1
  skip_cleanup: true
  on:
    branch: master
