#!/usr/bin/env bash

# Set script scope environment variables for dev or CI.
export APP_PORT=${APP_PORT:-80}
export CFN_TEMPLATE=${CFN_TEMPLATE:-cloudformation}

COMPOSE="docker-compose -f docker-compose.yml"

# Pass arguments to docker-compose, or default to docker-compose ps.
if [ $# -gt 0  ]; then
    case "$1" in

        composer )
            shift 1
            ${COMPOSE} run --rm \
                api \
                composer "$@"
            ;;

        npm )
            shift 1
            ${COMPOSE} run --rm \
                node \
                npm "$@"
            ;;

        cfn|cloudformation )
            docker-compose run --rm troposphere > aws/${CFN_TEMPLATE}.json
            cat aws/${CFN_TEMPLATE}.json
            ;;

        * ) ${COMPOSE} "$@"; ;;

    esac
else
    ${COMPOSE} ps
fi
