version: "3"

services:
  app:
    image: royal-borough-kingston/ck-frontend/app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html

  node:
    image: royal-borough-kingston/ck-frontend/node
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html

  troposphere:
    image: royal-borough-kingston/ck-frontend/troposphere
    build:
      context: ./docker/troposphere
      dockerfile: Dockerfile
    volumes:
      - ./aws:/tmp
    command: "python ${CFN_TEMPLATE}.py"
